# Railway / Production overrides

spring.thymeleaf.cache=true
seed.enabled=${SEED_ENABLED:false}

app.jwt.secret=${JWT_SECRET}

midtrans.server-key=${MIDTRANS_SERVER_KEY}
midtrans.client-key=${MIDTRANS_CLIENT_KEY}
midtrans.is-production=${MIDTRANS_IS_PRODUCTION}

spring.mail.host=${MAIL_HOST:smtp.sendgrid.net}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:apikey}
spring.mail.password=${MAIL_PASSWORD}
app.mail.from=${MAIL_FROM}
